"""Constants for the Chiltrix CX50 integration."""

DOMAIN = "chiltrix_cx50"

# Configuration constants
CONF_SLAVE_ID = "slave_id"
DEFAULT_PORT = 502
DEFAULT_SLAVE_ID = 1
DEFAULT_SCAN_INTERVAL = 30

# Register addresses (based on typical heat pump implementations)
# Note: These may need adjustment based on your specific CX50-2 model
REGISTER_WATER_INLET_TEMP = 0xCA  # 202
REGISTER_WATER_OUTLET_TEMP = 0xCB  # 203
REGISTER_AMBIENT_TEMP = 0xCC  # 204
REGISTER_COIL_TEMP = 0xCD  # 205
REGISTER_DISCHARGE_TEMP = 0xCE  # 206
REGISTER_SUCTION_TEMP = 0xCF  # 207
REGISTER_SETPOINT_TEMP = 0xD1  # 209
REGISTER_DHW_SETPOINT = 0xD5  # 213
REGISTER_ANTIFREEZE_TEMP = 0xD6  # 214
REGISTER_OPERATING_STATE = 0xF3  # 243
REGISTER_ERROR_CODE = 0xF4  # 244
REGISTER_CURRENT_POWER = 0x100  # 256
REGISTER_FLOW_RATE = 0x101  # 257
REGISTER_COMPRESSOR_SPEED = 0x102  # 258
REGISTER_FAN_SPEED = 0x103  # 259
REGISTER_PUMP_SPEED = 0x104  # 260
REGISTER_SYSTEM_PRESSURE = 0x105  # 261
REGISTER_RUN_HOURS = 0x108  # 264
REGISTER_COMPRESSOR_STARTS = 0x119  # 281

# Control registers
REGISTER_POWER_CONTROL = 0x00  # 0
REGISTER_MODE_CONTROL = 0x01  # 1
REGISTER_SETPOINT_CONTROL = 0xD1  # 209
REGISTER_DHW_SETPOINT_CONTROL = 0xD5  # 213
REGISTER_SILENT_MODE = 0x106  # 262
REGISTER_DHW_PRIORITY = 0x107  # 263

# Operating states
STATE_OFF = 0
STATE_HEATING = 1
STATE_COOLING = 2
STATE_AUTO = 3
STATE_DHW = 4
STATE_DEFROST = 5
STATE_ERROR = 6

# Temperature limits (in Celsius)
MIN_SETPOINT_TEMP = 15
MAX_SETPOINT_TEMP = 60
MIN_DHW_SETPOINT = 35
MAX_DHW_SETPOINT = 65
MIN_OUTLET_TEMP = 10
MAX_OUTLET_TEMP = 65
MIN_ANTIFREEZE_TEMP = -10
MAX_ANTIFREEZE_TEMP = 10

# Speed limits (percentage)
MIN_PUMP_SPEED = 20
MAX_PUMP_SPEED = 100
MIN_FAN_SPEED = 20
MAX_FAN_SPEED = 100

# Sensor units
UNIT_CELSIUS = "°C"
UNIT_WATTS = "W"
UNIT_KILOWATTS = "kW"
UNIT_LITERS_PER_MINUTE = "L/min"
UNIT_PERCENT = "%"
UNIT_BAR = "bar"
UNIT_HOURS = "h"

# Device classes
DEVICE_CLASS_TEMPERATURE = "temperature"
DEVICE_CLASS_POWER = "power"
DEVICE_CLASS_ENERGY = "energy"
DEVICE_CLASS_PRESSURE = "pressure"

# State classes
STATE_CLASS_MEASUREMENT = "measurement"
STATE_CLASS_TOTAL = "total"
STATE_CLASS_TOTAL_INCREASING = "total_increasing"
